name: Dev to Main Workflow

on:
  push:
    branches:
      - dev  # Déclenche sur les pushs dans la branche dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install

    - name: Install dependencies (Backend)
      working-directory: ./backend
      run: npm install

    - name: Run unit tests (Frontend)
      working-directory: ./frontend
      run: npm test

    - name: Run unit tests (Backend)
      working-directory: ./backend
      run: npm test

    - name: Build Docker images
      run: docker compose build

    - name: Push Docker images to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker compose push

    - name: Merge into main
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
